### PR TITLE
PJ_SIM_SUNBNB_2023-16 [FE] Reservation Component

### PR DESCRIPTION
**Pull request by LennardUy104**
# Issue Link
[PJ_SIM_SUNBNB_2023-16 [FE] Reservation Component ](https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-16)

# Definition of Done
* [x] Create a component for reservation for logged in clients with the components:
    * [x] Show Price Per Night
    * [x] Check In Date Input
    * [x] Check Out Date Input
    * [x] Book Now Button
 
# Notes
None

# Expected Output

image

# Screenshots/Recordings

image

### CODE REVIEW

**Comment by RonnieRII** [comment]
I think it would be better if the components were in red instead of grey to match the aesthetic of Sun*

**Comment by LennardUy104** [comment]
> I think it would be better if the components were in red instead of grey to match the aesthetic of Sun*

noted

**Comment by LennardUy104** [comment]
updated color theme already 
image

**Comment by RonnieRII** [comment]
Looks nice! Good job 👍

**Review by roseaugusto — APPROVED** [review]

**Pull request merged**
