### PR TITLE
PJ_SIM_SUNBNB_2023-19 [FE] Edit Profile Page

### PR DESCRIPTION
**Pull request by ThereseRoca**
# Issue Link
[PJ_SIM_SUNBNB_2023-19 [FE] Edit Profile Page](https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-19)

# Slack Link
https://sun-philippine.slack.com/archives/C05GURS7N3U/p1690807712537569

# Definition of Done
Create a markup for the edit profile page with the components:
- [x] Full Name Input Field
- [x] Phone Number Input Field
- [x] Description Text Field
- [x] Email Input Field
- [x] New Password Input Field
- [x] Confirm Password Input Field
- [x] Save Button
- [x] Input Validation

# Notes
installed vee-validate npm install vee-validate --save

# Expected Output
EditProfile

# Screenshots
image

### CODE REVIEW

**Comment by RonnieRII** [comment]
Please add a new line after the end of each file. Thank you! 🙇

**Comment by RonnieRII** [comment]
Please also remove the Reservation component. Thank you! 🙇 
image

**Review by LennardUy104 — COMMENTED** [review]
LGTM and working at my end, please squash all commits

**Comment by ThereseRoca** [comment]
> Please add a new line after the end of each file. Thank you! 🙇

**Comment by ThereseRoca** [comment]
> > Please add a new line after the end of each file. Thank you! 🙇
> 
> Done Ronnie Thanks

**Comment by ThereseRoca** [comment]
> LGTM and working at my end, please squash all commits
Done Andre. Thank you

**Comment by ThereseRoca** [comment]
> Please also remove the Reservation component. Thank you! 🙇 image

Done Ronnie. Thanks

**Pull request closed without merging**
