### PR TITLE
PJ_SIM_SUNBNB_2023-24 [FE] Listing Page or Room Page

### PR DESCRIPTION
**Pull request by LennardUy104**
# Issue Link
https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-24

# Definition of Done
* [ ] Create a markup for clients to see the full details of the listing with the components:
    * [ ] Slider Image of the Place
    * [ ] Listing Name
    * [ ] Home Type
    * [ ] Maximum Number of Guests
    * [ ] Number of Bathrooms
    * [ ] Number of Bedrooms
    * [ ] Reservation Components
    * [ ] Host Profile
    * [ ] Listing Description
    * [ ] Amenities
    * [ ] Suggested Listings

# Notes
Prepared the page markup
todo:
merge lacking components
* Reservation Component
* Review Component
* Listing Home Component

To Check 
I added a route into room just add `/room`

# Expected Output

image

# Screenshots/Recordings
image

image

image

### CODE REVIEW

**Review by andreenriquez11 — CHANGES_REQUESTED** [review]
- Please align "About This Listing", "Amenities", and the Reviews Component to the Listing Name.

image

- Kindly add a divider line after every section just like in the wireframe.

image

- Place the Reservation component on a fixed position on the lower left of the picture like in the wireframe.

image
image

- Add height to the image

image

- Add icons in here just like in the wireframe
image
image

- Place also an image placeholder for the owner of the listing and must be on the left of the reservation component.
image
image

- Follow arrangement in the wireframe
image
image

**Comment by LennardUy104** [comment]
@andreenriquez11 I have resolve all changes of Room Page, Please have a look

The reservation component will follow the user screen whenever the user scroll

image
image
image

**Review by andreenriquez11 — COMMENTED** [review]
- Too much space here between image and the content. Also, the image must not overlap the left and right of the content. It must be aligned on the same line.
image

- Reservation component still does not have a fix position on the lower right of the image or beside the listing owner
image

- Kindly make this smaller, I feel its kind of too big
image

**Comment by LennardUy104** [comment]
@andreenriquez11 

> * Too much space here between image and the content. Also, the image must not overlap the left and right of the content. It must be aligned on the same line.
>   image
> * Reservation component still does not have a fix position on the lower right of the image or beside the listing owner
>   image
> * Kindly make this smaller, I feel its kind of too big
>   image

I have fix these changes

**Review by andreenriquez11 — COMMENTED** [review]
Kindly cut divider line to not go underboard the reservation component

image

I think that's all. The others look good now. Thanks!

**Comment by LennardUy104** [comment]
> Kindly cut divider line to not go underboard the reservation component
> 
> image
> 
> I think that's all. The others look good now. Thanks!

@andreenriquez11 Already fixed

**Review by andreenriquez11 — APPROVED** [review]
Looks great now, thanks!

**Review by roseaugusto — APPROVED** [review]

**Pull request merged**
